

jpa:
  generate-ddl: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      jdbc:
        time_zone: UTC

hibernate:
  ddl-auto: update
  show-sql: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/puzzles
    username: root
    password: MySqlRootPass1#
  jpa:
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
